export type ProjectType = 'node' | 'python' | 'rust' | 'go' | 'java' | 'ruby' | 'unknown';
export type Preset = 'default' | 'balanced' | 'aggressive';

export function generateClaudeignore(
  projectType: ProjectType | string,
  preset: Preset | string,
): string {
  const lines: string[] = [
    '# .claudeignore — generated by claude-token-saver',
    '# Claude Code will not read files matching these patterns.',
    '',
    '# === Common ignores (all presets) ===',
    '.git/',
    'node_modules/',
    'dist/',
    'build/',
    '.cache/',
    'coverage/',
    '*.log',
    '.env',
    '.env.*',
    '!.env.example',
    '',
  ];

  // Language-specific ignores
  switch (projectType) {
    case 'python':
      lines.push(
        '# === Python ===',
        '__pycache__/',
        '*.pyc',
        '*.pyo',
        '*.pyd',
        '.venv/',
        'venv/',
        '*.egg-info/',
        '.mypy_cache/',
        '.pytest_cache/',
        '.ruff_cache/',
        '',
      );
      break;

    case 'rust':
      lines.push(
        '# === Rust ===',
        'target/',
        '*.rs.bk',
        '',
      );
      break;

    case 'go':
      lines.push(
        '# === Go ===',
        'vendor/',
        '*.test',
        '',
      );
      break;

    case 'java':
      lines.push(
        '# === Java ===',
        'target/',
        '*.class',
        '*.jar',
        '*.war',
        '.gradle/',
        'gradle/',
        '',
      );
      break;

    case 'ruby':
      lines.push(
        '# === Ruby ===',
        'vendor/bundle/',
        '.bundle/',
        '*.gem',
        '.byebug_history',
        '',
      );
      break;

    case 'node':
      lines.push(
        '# === Node.js ===',
        '.npm/',
        '.yarn/',
        '*.tsbuildinfo',
        '',
      );
      break;
  }

  // Preset-specific additions
  if (preset === 'balanced') {
    lines.push(
      '# === Balanced preset: generated/minified assets excluded ===',
      '*.min.js',
      '*.min.css',
      '*.map',
      '',
    );
  } else if (preset === 'aggressive') {
    lines.push(
      '# === Aggressive preset: docs, tests, and generated assets excluded ===',
      '# Docs',
      'docs/',
      'doc/',
      '*.md',
      '!CLAUDE.md',
      '!README.md',
      '',
      '# Tests',
      'test/',
      'tests/',
      '__tests__/',
      '*.test.ts',
      '*.test.js',
      '*.test.tsx',
      '*.spec.ts',
      '*.spec.js',
      '*.spec.tsx',
      'e2e/',
      'fixtures/',
      '',
      '# Generated/minified assets',
      '*.min.js',
      '*.min.css',
      '*.map',
      '',
    );
  }

  return lines.join('\n');
}
