import { ProjectInfo } from '../utils/scanner.js';

export type Preset = 'minimal' | 'balanced' | 'aggressive';

const BASE_PATTERNS = `# Dependencies
node_modules/
.venv/
__pycache__/
vendor/

# Build output
dist/
build/
out/
target/

# Secrets and credentials
.env
.env.*
*.pem
*.key
*.p12
*.pfx
`;

const BALANCED_PATTERNS = `
# Logs
*.log
logs/

# Test coverage
coverage/
.nyc_output/

# OS files
.DS_Store
Thumbs.db

# Editor
.vscode/
.idea/
*.swp
`;

const AGGRESSIVE_PATTERNS = `
# Package locks (often large)
package-lock.json
yarn.lock
pnpm-lock.yaml
poetry.lock
Cargo.lock

# Cache directories
.cache/
.parcel-cache/
.turbo/
.next/
.nuxt/

# Generated files
*.min.js
*.min.css
*.map
*.d.ts

# Test fixtures and snapshots
__snapshots__/
fixtures/
testdata/

# Documentation builds
docs/_build/
site/
`;

export function generateClaudeignore(preset: Preset, project: ProjectInfo): string {
  let content = `# .claudeignore — generated by claude-token-saver\n# Project: ${project.name} (${project.type})\n# Preset: ${preset}\n\n`;
  content += BASE_PATTERNS;

  if (preset === 'balanced' || preset === 'aggressive') {
    content += BALANCED_PATTERNS;
  }

  if (preset === 'aggressive') {
    content += AGGRESSIVE_PATTERNS;
  }

  return content;
}
