export type Preset = 'minimal' | 'balanced' | 'aggressive';

export function generateClaudeignore(preset: Preset = 'balanced'): string {
  const minimal = `# .claudeignore — files Claude should not read
# Generated by claude-token-saver

# Dependencies
node_modules/
vendor/
.venv/
venv/
__pycache__/
*.pyc

# Build artifacts
dist/
build/
out/
.next/
.nuxt/
coverage/

# Lock files (large, rarely useful)
package-lock.json
yarn.lock
pnpm-lock.yaml
composer.lock
Cargo.lock

# Sensitive files
.env
.env.*
*.key
*.pem
*.p12
*.pfx
secrets/
credentials/

# Logs
*.log
logs/
npm-debug.log*

# OS files
.DS_Store
Thumbs.db
Desktop.ini
`;

  const balancedExtra = `
# Editor / IDE
.idea/
.vscode/
*.swp
*.swo
*.suo
.vs/

# Test artifacts
.coverage
htmlcov/
*.snap
__snapshots__/

# Generated / minified
*.min.js
*.min.css
*.bundle.js
*.bundle.css
`;

  const aggressiveExtra = `
# Documentation (large, rarely needed in context)
docs/
doc/
*.pdf
*.docx
*.xlsx

# Images and media
*.png
*.jpg
*.jpeg
*.gif
*.svg
*.ico
*.mp4
*.mp3

# Data files
*.csv
*.json.bak
*.sql
*.dump
fixtures/
seeds/

# Cache directories
.cache/
.parcel-cache/
.turbo/
.nx/cache/
*.cache

# Test files (reduce context noise)
**/*.test.js
**/*.spec.js
**/*.test.ts
**/*.spec.ts
**/__tests__/
**/test/
**/tests/
`;

  if (preset === 'minimal') return minimal;
  if (preset === 'aggressive') return minimal + balancedExtra + aggressiveExtra;
  return minimal + balancedExtra;
}
