import { ProjectInfo } from '../utils/scanner.js';
import { Preset } from './claudeignore.js';

export function generateClaudemd(preset: Preset, project: ProjectInfo): string {
  const lines: string[] = [
    `# ${project.name}`,
    '',
    `> Generated by claude-token-saver · preset: ${preset}`,
    '',
  ];

  lines.push('## Project');
  lines.push('');
  lines.push(`- **Type**: ${project.type}`);
  if (project.hasGit) lines.push('- **VCS**: git');
  lines.push('');

  lines.push('## Development');
  lines.push('');

  if (project.type === 'node') {
    lines.push('- Install: `npm install`');
    lines.push('- Build: `npm run build`');
    lines.push('- Test: `npm test`');
  } else if (project.type === 'python') {
    lines.push('- Install: `pip install -r requirements.txt`');
    lines.push('- Test: `pytest`');
  } else if (project.type === 'go') {
    lines.push('- Build: `go build ./...`');
    lines.push('- Test: `go test ./...`');
  } else if (project.type === 'rust') {
    lines.push('- Build: `cargo build`');
    lines.push('- Test: `cargo test`');
  } else {
    lines.push('- _Fill in build and test commands_');
  }

  lines.push('');

  if (preset === 'balanced' || preset === 'aggressive') {
    lines.push('## Guidelines');
    lines.push('');
    lines.push('- Write tests for new functionality');
    lines.push('- Keep PRs focused and small');
    lines.push('- Follow existing code style');
    lines.push('');
  }

  if (preset === 'aggressive') {
    lines.push('## Constraints');
    lines.push('');
    lines.push('- Do not modify generated files');
    lines.push('- Do not add dependencies without discussion');
    lines.push('- Keep functions small and focused');
    lines.push('- Avoid global state');
    lines.push('');
  }

  return lines.join('\n');
}
