export interface HookScripts {
  'session-start.sh': string;
  'post-tool.sh': string;
  'pre-compact.sh': string;
}

export type Preset = 'default' | 'balanced' | 'aggressive';

export function generateHooks(
  projectType: string = 'unknown',
  preset: Preset | string = 'default',
): HookScripts {
  // ─── session-start.sh ────────────────────────────────────────────────────
  // Runs at the start of every Claude Code session.
  // Prints git context (branch, recent commits) and reminds about /compact.
  const sessionStart = `#!/bin/sh
# session-start.sh — generated by claude-token-saver
# Runs at the start of each Claude Code session.
# Prints git context and a /compact reminder to help manage token usage.

DATA_DIR=\${CTS_DATA_DIR:-"\$HOME/.claude-token-saver"}
TRACKING_FILE="\$DATA_DIR/tracking.json"
TIMESTAMP=$(date -u +"%Y-%m-%dT%H:%M:%SZ")

# ── Git context ──────────────────────────────────────────────────────────────
if command -v git >/dev/null 2>&1; then
  PROJECT=$(git rev-parse --show-toplevel 2>/dev/null || echo "unknown")
  BRANCH=$(git rev-parse --abbrev-ref HEAD 2>/dev/null || echo "unknown")
  RECENT=$(git log --oneline -5 2>/dev/null || echo "(no commits)")

  echo "=== Git context ==="
  echo "Project : \$PROJECT"
  echo "Branch  : \$BRANCH"
  echo "Recent commits:"
  echo "\$RECENT"
  echo ""
else
  PROJECT="unknown"
  BRANCH="unknown"
  echo "=== Session started (git not available) ==="
  echo ""
fi

# ── /compact reminder ────────────────────────────────────────────────────────
echo "Tip: run /compact when context grows large to save tokens."
echo ""

# ── Record session start ─────────────────────────────────────────────────────
mkdir -p "\$DATA_DIR"

if [ ! -f "\$TRACKING_FILE" ]; then
  echo '{"sessions":[]}' > "\$TRACKING_FILE"
fi

if command -v node >/dev/null 2>&1; then
  node - "\$TRACKING_FILE" "\$TIMESTAMP" "\$PROJECT" "\$BRANCH" <<'EOF'
const fs = require('fs');
const [,, file, timestamp, project, branch] = process.argv;
let data;
try { data = JSON.parse(fs.readFileSync(file, 'utf-8')); } catch { data = { sessions: [] }; }
data.sessions.push({ timestamp, project, branch });
fs.writeFileSync(file, JSON.stringify(data, null, 2));
EOF
else
  echo "cts session-start: node not available, skipping session record" >&2
fi
`;

  // ─── post-tool.sh ─────────────────────────────────────────────────────────
  // Runs after each tool call. Logs tool usage for token tracking.
  const postTool = `#!/bin/sh
# post-tool.sh — generated by claude-token-saver
# Runs after each tool call. Logs tool usage data for token consumption tracking.

if ! command -v node >/dev/null 2>&1; then
  echo "cts post-tool: node not available, skipping" >&2
  exit 0
fi

DATA_DIR=\${CTS_DATA_DIR:-"\$HOME/.claude-token-saver"}
TRACKING_FILE="\$DATA_DIR/tracking.json"

if [ ! -f "\$TRACKING_FILE" ]; then
  exit 0
fi

# Claude Code provides a JSON event on stdin describing the tool call
node - "\$TRACKING_FILE" <<'EOF'
const fs = require('fs');
const [,, file] = process.argv;
let input = '';
process.stdin.on('data', (d) => { input += d; });
process.stdin.on('end', () => {
  let event;
  try { event = JSON.parse(input); } catch { process.exit(0); }
  let data;
  try { data = JSON.parse(fs.readFileSync(file, 'utf-8')); } catch { data = { sessions: [] }; }
  if (!data.toolCalls) data.toolCalls = [];
  data.toolCalls.push({
    timestamp: new Date().toISOString(),
    tool: event.tool_name ?? event.tool ?? 'unknown',
    event,
  });
  fs.writeFileSync(file, JSON.stringify(data, null, 2));
});
EOF
`;

  // ─── pre-compact.sh ───────────────────────────────────────────────────────
  // Runs before Claude Code performs a /compact operation.
  // Prints compaction rules so Claude has fresh guidance after the summary.
  const compactRules = buildCompactRules(projectType, preset);
  const preCompact = `#!/bin/sh
# pre-compact.sh — generated by claude-token-saver
# Runs before each /compact operation.
# Echoes compaction rules so they survive into the compacted context.

cat <<'RULES'
=== Compaction rules (claude-token-saver / preset: ${preset}) ===

${compactRules}
RULES

# Record compaction event
DATA_DIR=\${CTS_DATA_DIR:-"\$HOME/.claude-token-saver"}
TRACKING_FILE="\$DATA_DIR/tracking.json"

if command -v node >/dev/null 2>&1 && [ -f "\$TRACKING_FILE" ]; then
  node - "\$TRACKING_FILE" <<'EOF'
const fs = require('fs');
const [,, file] = process.argv;
let data;
try { data = JSON.parse(fs.readFileSync(file, 'utf-8')); } catch { data = { sessions: [] }; }
if (!data.compactions) data.compactions = [];
data.compactions.push({ timestamp: new Date().toISOString() });
fs.writeFileSync(file, JSON.stringify(data, null, 2));
EOF
fi
`;

  return {
    'session-start.sh': sessionStart,
    'post-tool.sh': postTool,
    'pre-compact.sh': preCompact,
  };
}

function buildCompactRules(projectType: string, preset: string): string {
  const rules: string[] = [];

  // Universal rules
  rules.push('ALWAYS retain:');
  rules.push('  - The original task / user request');
  rules.push('  - File paths and function names already identified');
  rules.push('  - Any decisions made or approaches agreed with the user');
  rules.push('  - Outstanding TODO items or next steps');
  rules.push('');
  rules.push('OMIT from summary:');
  rules.push('  - Full file contents already read (keep paths + key excerpts only)');
  rules.push('  - Redundant error messages already resolved');
  rules.push('  - Tool call traces for completed, non-controversial actions');

  if (preset === 'balanced' || preset === 'aggressive') {
    rules.push('');
    rules.push('BALANCED / AGGRESSIVE extra rules:');
    rules.push('  - Summarise test output as pass/fail counts, not full output');
    rules.push('  - Drop read file contents when the key info is captured elsewhere');
    rules.push('  - Collapse repeated tool-call patterns into a single sentence');
  }

  if (preset === 'aggressive') {
    rules.push('');
    rules.push('AGGRESSIVE extra rules:');
    rules.push('  - Maximum summary length: 100 lines');
    rules.push('  - One sentence per resolved sub-task');
    rules.push('  - No inline code blocks unless strictly necessary for context');
    rules.push('  - Drop all conversational filler from the summary');
  }

  if (projectType !== 'unknown') {
    rules.push('');
    rules.push(`Project type: ${projectType} — preserve any language-specific context`);
    rules.push('  (e.g. module paths, build flags, test harness details)');
  }

  return rules.join('\n');
}
